# Generated by Django 3.0.4 on 2020-03-30 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='artist',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
