# Generated by Django 3.0.5 on 2020-04-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20200330_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='credit_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artefact',
            name='dimensions',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
