# Generated by Django 3.0.5 on 2020-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20200416_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='accession_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='credit_line',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
