# Generated by Django 3.0.5 on 2020-04-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20200417_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
